name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prantlf/setup-v-action@v2
      - uses: prantlf/bump-version-action@v2
